Split code into separate components
ProtocolONE/authone-jwt-verifier-golang pull request #1
Opened 2019-02-20 18:15 UTC by pr0head

2019-02-20 18:25 UTC, misterion requested changes
Добавляйте тесте везде - их катастрофически нет

2019-02-20 18:25 UTC, misterion commented on storage/memory/memory_storage.go
> +func NewStogare(maxSize int64, itemsToPrune uint32) storage.Adapter {
тут лучше ...options и из них считать уже параметры, чтобы была возможность инстанцирлвать его без параметров (с данными по умолчанию)

2019-02-20 18:25 UTC, misterion commented on README.md
> +	// Init login middleware
Устарело - поправить

2019-02-20 18:25 UTC, misterion commented on storage/redis/redis_storage.go
> +	return redisStorage{redis: c, key: "a_t_s_%s"}
ключ:значение - иначе вас проклянут на анализе данных в редисе

2019-02-20 18:25 UTC, misterion commented on types.go
> +type IntrospectToken struct {
Док блок

2019-02-21 10:39 UTC, pr0head commented on storage/memory/memory_storage.go
> +func NewStogare(maxSize int64, itemsToPrune uint32) storage.Adapter {
fixed

2019-02-21 10:39 UTC, pr0head commented on storage/redis/redis_storage.go
> +	return redisStorage{redis: c, key: "a_t_s_%s"}
fixed

2019-02-21 10:39 UTC, pr0head commented on types.go
> +type IntrospectToken struct {
fixed

2019-02-25 08:46 UTC, misterion requested changes

2019-02-25 08:46 UTC, misterion commented on internal/types.go
> +// Repeats the structure of the Introspect Token object described in the Hydra documentation.
Doc блок в некорректном формате по godoc

2019-02-25 08:46 UTC, misterion commented on internal/types.go
> +// Based at JWT claims.
Doc блок в некорректном формате по godoc

2019-02-25 08:46 UTC, misterion commented on internal/types.go
> +// https://www.iana.org/assignments/jwt/jwt.xhtml
Doc блок в некорректном формате по godoc

2019-02-25 08:46 UTC, misterion commented on internal/types.go
> +type Token struct {
Пропущен doc block

2019-02-25 08:46 UTC, misterion commented on internal/types.go
> +type RetrieveError struct {
Пропущен docblock

2019-02-25 08:46 UTC, misterion commented on internal/types.go
> +	return fmt.Sprintf("oauth2: cannot fetch token: %v\nResponse: %s", r.Response.Status, r.Body)
oauth2?

2019-02-25 08:46 UTC, misterion commented on jwtverifier.go
> +type JwtVerifier struct {
Пропущен doc block

2019-02-25 08:46 UTC, misterion commented on jwtverifier.go
> +// An additional option for authentication form URL
Doc блок в некорректном формате по godoc

2019-02-25 08:46 UTC, misterion commented on jwtverifier.go
> +// Set storage adapter for the introspection token.
Doc блок в некорректном формате по godoc

2019-02-25 08:46 UTC, misterion commented on jwtverifier.go
> +// Create a URL to send the user to the initial authentication step.
Doc блок в некорректном формате по godoc

2019-02-25 08:46 UTC, misterion commented on jwtverifier.go
> +// Check a token refresh or access is active or not. An active token is neither expired nor revoked.
Doc блок в некорректном формате по godoc

2019-02-25 08:46 UTC, misterion commented on internal/types.go
> +package internal
зачем internal? тут должен быть основной пакет!

2019-02-25 08:46 UTC, misterion commented on jwtverifier.go
> +	fmt.Printf("url: %+v\n", buf.String())
wtf Printf?

2019-02-25 08:46 UTC, misterion commented on jwtverifier.go
> +	var buf bytes.Buffer
Зачем вам тут буфер если вы с ним как со строкой работаете и строку же и возвращаете?

2019-02-25 08:46 UTC, misterion commented on jwtverifier.go
> +	if introspect, _ := j.getIntrospectFromStorage(token); introspect != nil {
Странная проверка. Почему ошибка игнорируется?

2019-02-25 08:46 UTC, misterion commented on jwtverifier.go
> +func (j *JwtVerifier) getTokenStorage() (storage.Adapter, error) {
Это левый метод -  у вас срабатывает или дефолтный конструктор в котором вы сами задаете хранилизе или его берут из аргументов при создании. Тут ленивая инициализация не нужна

2019-02-25 08:46 UTC, misterion commented on jwtverifier.go
> +func (j *JwtVerifier) getIntrospectFromStorage(token string) (*internal.IntrospectToken, error) {
см. выше

2019-02-25 08:46 UTC, misterion commented on jwtverifier.go
> +func (j *JwtVerifier) saveIntrospectToStorage(token string, source *internal.IntrospectToken) error {
см. выше

2019-02-25 08:46 UTC, misterion commented on storage/memory/memory_storage.go
> +func NewStorage(options map[string]interface{}) storage.Adapter {
Переделайте на slice аргeментов или на конкретные - передавать структура как в php не нужно. Нет в этом никакой пользы

2019-02-25 08:46 UTC, misterion commented on storage/redis/redis_storage.go
> +func NewStorage(c *redis.Client) storage.Adapter {
А вот тут, в slice аргументах не хватает передачи пространства имен не по умолчанию

2019-02-25 17:02 UTC, merged